#pragma once

#define IDI_APP                         101
#define IDI_TRAY_ARMED                  102
#define IDI_TRAY_WARNING                103
#define IDI_TRAY_PROTECTED              104
#define IDI_TRAY_FAULT                  105
#define IDI_CAMERA                      106
#define IDD_MAIN                        201
#define IDC_GPU_NAME                    1001
#define IDC_GPU_TEMP                    1002
#define IDC_GPU_POWER                   1003
#define IDC_GPU_LIMIT                   1004
#define IDC_GPU_THERMAL                 1005
#define IDC_STATUS                      1006
#define IDC_TEMP_LABEL                  1007
#define IDC_POWER_LABEL                 1008
#define IDC_STATUS_ICON                 1009
#define IDC_NORMAL_POWER                1010
#define IDC_SAFE_POWER                  1011
#define IDC_TRIGGER_TEMP                1012
#define IDC_HISTORY                     1013
#define IDC_SAVE_SETTINGS               1020
#define IDC_HIDE_TO_TRAY                1021
#define IDC_CLOSE_TO_TRAY               1022
#define IDC_OSD_ENABLED                 1023
#define IDC_WALL_TIME                   1024
#define IDC_CAPTURE_SNAPSHOT            1025
#define IDC_VRAM_LABEL                  1026
#define IDC_GPU_VRAM                    1027
#define IDC_LANGUAGE                    1028
#define IDC_STATUS_GROUP                1029
#define IDC_GPU_LABEL                   1030
#define IDC_LIMIT_LABEL                 1031
#define IDC_THERMAL_LABEL               1032
#define IDC_HISTORY_GROUP               1033
#define IDC_SETTINGS_GROUP              1034
#define IDC_NORMAL_POWER_LABEL          1035
#define IDC_SAFE_POWER_LABEL            1036
#define IDC_TRIGGER_TEMP_LABEL          1037
#define IDC_SETTINGS_NOTE               1038
#define IDC_TRIGGER_COUNT               1039
#define IDC_AUTO_RESTORE                1040
#define IDC_VBIOS_LABEL                 1041
#define IDC_GPU_VBIOS                   1042
#define IDC_RESET_TRIGGER_COUNT         1043
#define IDC_SHOW_FPS                    1044
#define IDC_SHOW_RAM                    1045
#define IDC_SHOW_NET                    1046
#define IDM_TRAY_OPEN                   40001
#define IDM_TRAY_REFRESH                40002
#define IDM_TRAY_EXIT                   40003
#define IDM_TRAY_OPEN_LOG               40004
#define IDM_TRAY_TOGGLE_OSD             40005
#define IDM_TRAY_CAPTURE_SNAPSHOT       40006
#define IDM_TRAY_RESET_OSD_LAYOUT       40007
#define IDM_TRAY_DEEP_MEMORY_CLEAN      40008
